### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by vincenzopalazzo** [isp-insoft-gmbh/SwingX#4]
Hello 
I'm a junior java developer and I'm a fan for swing and I'm a contributor for [material-ui-swing](https://github.com/atarw/material-ui-swing).
I think for creating a new component for java swing with the java swingx project and example
- [Toast component](https://github.com/vincenzopalazzo/toasts-for-swing)
- [Material Color Chooser style](https://github.com/vincenzopalazzo/material-ui-swing/issues/42)
- [Material Task Pane style](https://github.com/vincenzopalazzo/material-ui-swing/issues/30)

But i'm a student and not have more time for work in the project only, if you want We can join forces to create a 2.0 version that makes swing a more current framework.

I am willing to help into this project.

Let me know.
Vincent

**Comment by Bios-Marcel** [comment]
Hey,

for now our main priority isn't adding feature, but fixing bugs, cleaning up and moving to a more recent release of the JDK. Whether this intention will change with time or not, is currently not clear.

Anyway, do I understand it correctly, that you want to create a complete material UI Look&Feel for swingx and upstream it to this fork?

**Comment by vincenzopalazzo** [comment]
Hi @Bios-Marcel,

Your work is good because the swingx is the very good framework me too have an idea for working on this project but I didn't have time. if I have time  free I will try to help you with this project if you are agree.

> for now our main priority isn't adding feature, but fixing bugs, cleaning up and moving to a more recent release of the JDK. Whether this intention will change with time or not, is currently not cle

The Swing is my referiment framework because into univerity I study java and swing for create a GUI so invest the time on swing for create a modern GUI is a good idea for me.
I want create a framework modern for swing because this help me in the my future personal work.
It will cool idea if add the support component material into this project because the component style material is more requested at this moment

> Anyway, do I understand it correctly, that you want to create a complete material UI Look&Feel for swingx and upstream it to this fork?

Sorry my terrible English but I'm learning

**Comment by bugabinga** [comment]
Hi @vincenzopalazzo !

Glad to see your interest in the project.
If you are motivated to add a "Material Design Look and Feel" to SwingX, create an issue outlining a plan to achieve that.
We would certainly help with planning and designing the L&F and also integrating it in a maintainable fashion.

I can see, that you have a working proof of concept in the repo you linked.
As such, it would not take much to integrate it into SwingX.
What you need is a test suite, some documentation and a plan forward (what features are missing in ´mdlaf´?)

However, since we do not have a need for it ourselves, it is unlikely that we will be able to put a lot of time into coding it up.
In the short term future, our goal will be to clean up the code base as outlined in #3, as @Bios-Marcel  suggested.
Feel free to start working on those and ask any question you need,

**Comment by vincenzopalazzo** [comment]
Hi @bugabinga,

Thank you for work into this beautiful project.

The material-ui-swing is in the beta test ant it will ready I try add support into swingx, thanks so much.

For moment I am working on the version stable material-ui-swing and in to free time I hope to try help you for this project

 Thanks so much and good work
